# ETL Pipeline – Slutuppgift Data Science

Denna notebook implementerar en ETL-pipeline som körs på två dataset:
- main dataset
- validation dataset

In [1]:
!pip install pandas numpy python-dotenv matplotlib seaborn langchain langchain_groq

Collecting pandas
  Downloading pandas-3.0.0-cp314-cp314-macosx_10_15_x86_64.whl.metadata (79 kB)
Collecting numpy
  Using cached numpy-2.4.1-cp314-cp314-macosx_14_0_x86_64.whl.metadata (6.6 kB)
Collecting python-dotenv
  Using cached python_dotenv-1.2.1-py3-none-any.whl.metadata (25 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp314-cp314-macosx_10_13_x86_64.whl.metadata (52 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting langchain
  Using cached langchain-1.2.6-py3-none-any.whl.metadata (4.9 kB)
Collecting langchain_groq
  Using cached langchain_groq-1.1.1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp314-cp314-macosx_10_13_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.61.1-cp314-cp314-macosx_10_15_x86_64.whl.metadata (114 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.9-cp314-cp314-macosx_10_13_x86_64.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.14/site-packages (from matplotlib) (26.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.1.0-cp314-cp314-macosx_10_15_x86_64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting langchain-core<2.0.0,>=1.2.7 (from langchain)
  Using cached langchain_core-1.2.7-py3-none-any.whl.metadata (3.7 kB)
Collecting langgraph<1.1.0,>=1.0.2 (from langchain)
  Using cached langgraph-1.0.6-py3-none-any.whl.metadata (7.4 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain)
  Using cached pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain-core<2.0.0,>=1.2.7->langchain)
  Using cached jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core<2.0.0,>=1.2.7->langchain)
  Using cached langsmith-0.6.4-py3-none-any.whl.metadata (15 kB)
Collecting packaging>=20.0 (from matplotlib)
  Using cached packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pyyaml<7.0.0,>=5.3.0 (from langchain-core<2.0.0,>=1.2.7->langchain)
  Using cached pyyaml-6.0.3-cp314-cp314-macosx_10_13_x86_64.whl.metadata (2.4 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain-core<2.0.0,>=1.2.7->langchain)
  Using cached tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)
Collecting typing-extensions<5.0.0,>=4.7.0 (from langchain-core<2.0.0,>=1.2.7->langchain)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core<2.0.0,>=1.2.7->langchain)
  Using cached uuid_utils-0.14.0-cp39-abi3-macosx_10_12_x86_64.whl.metadata (4.9 kB)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.7->langchain)
  Using cached jsonpointer-3.0.0-py2.py3-none-any.whl.metadata (2.3 kB)
Collecting langgraph-checkpoint<5.0.0,>=2.1.0 (from langgraph<1.1.0,>=1.0.2->langchain)
  Using cached langgraph_checkpoint-4.0.0-py3-none-any.whl.metadata (4.9 kB)
Collecting langgraph-prebuilt<1.1.0,>=1.0.2 (from langgraph<1.1.0,>=1.0.2->langchain)
  Using cached langgraph_prebuilt-1.0.6-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.4.0,>=0.3.0 (from langgraph<1.1.0,>=1.0.2->langchain)
  Using cached langgraph_sdk-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting xxhash>=3.5.0 (from langgraph<1.1.0,>=1.0.2->langchain)
  Using cached xxhash-3.6.0-cp314-cp314-macosx_10_13_x86_64.whl.metadata (13 kB)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain)
  Downloading ormsgpack-1.12.2-cp314-cp314-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl.metadata (3.2 kB)
Collecting httpx>=0.25.2 (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting orjson>=3.10.1 (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain)
  Using cached orjson-3.11.5-cp314-cp314-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl.metadata (41 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain)
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting requests>=2.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain)
  Using cached zstandard-0.25.0-cp314-cp314-macosx_10_13_x86_64.whl.metadata (3.3 kB)
Collecting anyio (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain)
  Using cached anyio-4.12.1-py3-none-any.whl.metadata (4.3 kB)
Collecting certifi (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain)
  Using cached certifi-2026.1.4-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic<3.0.0,>=2.7.4->langchain)
  Using cached pydantic_core-2.41.5-cp314-cp314-macosx_10_12_x86_64.whl.metadata (7.3 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.7.4->langchain)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting groq<1.0.0,>=0.30.0 (from langchain_groq)
  Using cached groq-0.37.1-py3-none-any.whl.metadata (16 kB)
Collecting distro<2,>=1.7.0 (from groq<1.0.0,>=0.30.0->langchain_groq)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting sniffio (from groq<1.0.0,>=0.30.0->langchain_groq)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting charset_normalizer<4,>=2 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain)
  Using cached charset_normalizer-3.4.4-cp314-cp314-macosx_10_13_universal2.whl.metadata (37 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.7->langchain)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Downloading pandas-3.0.0-cp314-cp314-macosx_10_15_x86_64.whl (10.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 23.7 MB/s  0:00:00m0:00:010:01
Using cached numpy-2.4.1-cp314-cp314-macosx_14_0_x86_64.whl (6.5 MB)
Using cached python_dotenv-1.2.1-py3-none-any.whl (21 kB)
Using cached matplotlib-3.10.8-cp314-cp314-macosx_10_13_x86_64.whl (8.3 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached langchain-1.2.6-py3-none-any.whl (108 kB)
Using cached langchain_core-1.2.7-py3-none-any.whl (490 kB)
Using cached jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Using cached langgraph-1.0.6-py3-none-any.whl (157 kB)
Using cached langgraph_checkpoint-4.0.0-py3-none-any.whl (46 kB)
Using cached langgraph_prebuilt-1.0.6-py3-none-any.whl (35 kB)
Using cached langgraph_sdk-0.3.3-py3-none-any.whl (67 kB)
Using cached langsmith-0.6.4-py3-none-any.whl (283 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached packaging-25.0-py3-none-any.whl (66 kB)
Using cached pydantic-2.12.5-py3-none-any.whl (463 kB)
Using cached pydantic_core-2.41.5-cp314-cp314-macosx_10_12_x86_64.whl (2.1 MB)
Using cached pyyaml-6.0.3-cp314-cp314-macosx_10_13_x86_64.whl (181 kB)
Using cached tenacity-9.1.2-py3-none-any.whl (28 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached uuid_utils-0.14.0-cp39-abi3-macosx_10_12_x86_64.whl (303 kB)
Using cached langchain_groq-1.1.1-py3-none-any.whl (19 kB)
Using cached groq-0.37.1-py3-none-any.whl (137 kB)
Using cached anyio-4.12.1-py3-none-any.whl (113 kB)
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached contourpy-1.3.3-cp314-cp314-macosx_10_13_x86_64.whl (292 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.61.1-cp314-cp314-macosx_10_15_x86_64.whl (2.4 MB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached jsonpointer-3.0.0-py2.py3-none-any.whl (7.6 kB)
Using cached kiwisolver-1.4.9-cp314-cp314-macosx_10_13_x86_64.whl (66 kB)
Using cached orjson-3.11.5-cp314-cp314-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl (245 kB)
Downloading ormsgpack-1.12.2-cp314-cp314-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl (378 kB)
Downloading pillow-12.1.0-cp314-cp314-macosx_10_15_x86_64.whl (5.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 38.4 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.4-cp314-cp314-macosx_10_13_universal2.whl (207 kB)
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Using cached certifi-2026.1.4-py3-none-any.whl (152 kB)
Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached xxhash-3.6.0-cp314-cp314-macosx_10_13_x86_64.whl (32 kB)
Using cached zstandard-0.25.0-cp314-cp314-macosx_10_13_x86_64.whl (795 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Installing collected packages: zstandard, xxhash, uuid-utils, urllib3, typing-extensions, tenacity, sniffio, pyyaml, python-dotenv, pyparsing, pillow, packaging, ormsgpack, orjson, numpy, kiwisolver, jsonpointer, idna, h11, fonttools, distro, cycler, charset_normalizer, certifi, annotated-types, typing-inspection, requests, pydantic-core, pandas, jsonpatch, httpcore, contourpy, anyio, requests-toolbelt, pydantic, matplotlib, httpx, seaborn, langsmith, langgraph-sdk, groq, langchain-core, langgraph-checkpoint, langchain_groq, langgraph-prebuilt, langgraph, langchain
  Attempting uninstall: packaging0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/47 [pillow]ng]ensions]
    Found existing installation: packaging 26.0━━━━━━━━━━━━━━━ 10/47 [pillow]
    Uninstalling packaging-26.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/47 [pillow]
      Successfully uninstalled packaging-26.0━━━━━━━━━━━━━━━━━━━━━ 11/47 [packaging]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47/47 [langchain]47 [langgraph]core]
Successfully installed annotated-types-0.7.0 anyio-4.12.1 certifi-2026.1.4 charset_normalizer-3.4.4 contourpy-1.3.3 cycler-0.12.1 distro-1.9.0 fonttools-4.61.1 groq-0.37.1 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 idna-3.11 jsonpatch-1.33 jsonpointer-3.0.0 kiwisolver-1.4.9 langchain-1.2.6 langchain-core-1.2.7 langchain_groq-1.1.1 langgraph-1.0.6 langgraph-checkpoint-4.0.0 langgraph-prebuilt-1.0.6 langgraph-sdk-0.3.3 langsmith-0.6.4 matplotlib-3.10.8 numpy-2.4.1 orjson-3.11.5 ormsgpack-1.12.2 packaging-25.0 pandas-3.0.0 pillow-12.1.0 pydantic-2.12.5 pydantic-core-2.41.5 pyparsing-3.3.2 python-dotenv-1.2.1 pyyaml-6.0.3 requests-2.32.5 requests-toolbelt-1.0.0 seaborn-0.13.2 sniffio-1.3.1 tenacity-9.1.2 typing-extensions-4.15.0 typing-inspection-0.4.2 urllib3-2.6.3 uuid-utils-0.14.0 xxhash-3.6.0 zstandard-0.25.0

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: pip install --upgrade pip

# IMPORTERA BIBLOTEK OCH LLM

Här kommer alla importer jag behöver för att kunna slutföra uppgiften.
Även här så kommer jag att ha min LLM.

In [2]:
import os
import time
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from dotenv import load_dotenv
load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
assert GROQ_API_KEY, "Saknar GROQ_API_KEY i .env"

In [3]:
from langchain_groq import ChatGroq

llm = ChatGroq(
    model="openai/gpt-oss-120b",
    temperature=0
)

if llm:
    print("LLM is initialized")

/Users/rikardsoderstrom/DataScience-uppgift/venv/lib/python3.14/site-packages/langchain_core/_api/deprecation.py:26: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1.fields import FieldInfo as FieldInfoV1

LLM is initialized

# Ladda in och inspektera dataset

In [10]:
df_raw = pd.read_csv("nordtech_data.csv")

df_raw.head()

,order_id,orderrad_id,orderdatum,leveransdatum,produkt_sku,produktnamn,kategori,antal,pris_per_enhet,region,kundtyp,betalmetod,kund_id,leveransstatus,recension_text,recensionsdatum,betyg
0,ORD-2024-00001,ORD-2024-00001-1,2024-05-19,2024-05-22,SKU-WC001,Webbkamera HD,Tillbehör,1,SEK 799,Uppsala,Privat,Kort,KND-53648,Levererad,NaN,NaN,NaN
1,ORD-2024-00002,ORD-2024-00002-1,2024-12-02,5 december 2024,SKU-HB001,USB-C Hub 7-port,Tillbehör,1,549.00,Göteborg,Privat,Swish,KND-84095,Levererad,NaN,NaN,NaN
2,ORD-2024-00003,ORD-2024-00003-1,2024-12-31,2025-01-03,SKU-SD001,Extern SSD 1TB,Lagring,1,1199.00,NaN,Företag,Faktura,KND-91748,Levererad,Stämmer inte överens med produktbeskrivningen.,2025-01-12,2.0
3,ORD-2024-00003,ORD-2024-00003-2,2024-12-31,2025-01-03,SKU-SD002,Extern SSD 500GB,Lagring,10,699 kr,Stockholm,Företag,FAKTURA,KND-91748,Mottagen,"Leveransen tog lite längre än utlovat, men pro...",2025-01-14,3.0
4,ORD-2024-00003,ORD-2024-00003-3,2024-12-31,2025-01-03,SKU-MS001,Trådlös Mus X1,Tillbehör,1,399.00,Stockholm,Företag,Faktura,KND-91748,NaN,NaN,NaN,NaN

In [11]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 2767 entries, 0 to 2766
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         2767 non-null   str
 1   orderrad_id      2767 non-null   str
 2   orderdatum       2767 non-null   str
 3   leveransdatum    2767 non-null   str
 4   produkt_sku      2767 non-null   str
 5   produktnamn      2767 non-null   str
 6   kategori         2767 non-null   str
 7   antal            2767 non-null   str
 8   pris_per_enhet   2767 non-null   str
 9   region           2612 non-null   str
 10  kundtyp          2767 non-null   str
 11  betalmetod       2651 non-null   str
 12  kund_id          2767 non-null   str
 13  leveransstatus   2673 non-null   str
 14  recension_text   1355 non-null   str
 15  recensionsdatum  1355 non-null   str
 16  betyg            1355 non-null   float64
dtypes: float64(1), str(16)
memory usage: 367.6 KB

In [12]:
df_raw.tail()

,order_id,orderrad_id,orderdatum,leveransdatum,produkt_sku,produktnamn,kategori,antal,pris_per_enhet,region,kundtyp,betalmetod,kund_id,leveransstatus,recension_text,recensionsdatum,betyg
2762,ORD-2024-01654,ORD-2024-01654-3,2024-10-04,2024-10-07,SKU-LP003,Laptop Gaming X,Datorer,2,18999.00,stockholm,Företag,NaN,KND-99742,Levererad,"Förväntade mig mer för priset, men den duger.",2024-10-08,3.0
2763,ORD-2024-01655,ORD-2024-01655-1,2024-01-15,2024-01-17,SKU-MN003,"Bildskärm 32"" Curved",Bildskärmar,1,5999.00,Göteborg,Privat,Faktura,KND-83827,Returnerad,Stämmer inte överens med produktbeskrivningen.,2024-01-27,2.0
2764,ORD-2024-01656,ORD-2024-01656-1,2024-07-29,2024-07-31,SKU-MS002,Ergonomisk Mus Pro,Tillbehör,1,699.00,göteborg,Privat,faktura,KND-60471,Levererad,NaN,NaN,NaN
2765,ORD-2024-01656,ORD-2024-01656-2,2024-07-29,2024-07-31,SKU-MN001,"Bildskärm 27"" UHD",Bildskärmar,1,4999.00,Göteborg,Konsument,Faktura,KND-60471,Levererad,NaN,NaN,NaN
2766,ORD-2024-01657,ORD-2024-01657-1,2024-07-03,2024-07-05,SKU-MN002,"Bildskärm 24"" FHD",Bildskärmar,1,2499.00,STOCKHOLM,Privat,NaN,KND-26325,levererad,Överträffade mina förväntningar. 5 av 5!,2024-07-08,4.0

In [13]:
df_raw.sample(10)

,order_id,orderrad_id,orderdatum,leveransdatum,produkt_sku,produktnamn,kategori,antal,pris_per_enhet,region,kundtyp,betalmetod,kund_id,leveransstatus,recension_text,recensionsdatum,betyg
2010,ORD-2024-01205,ORD-2024-01205-1,2024-05-06,2024-05-08,SKU-HS001,Headset Pro ANC,Ljud,2,SEK 1899,Stockholm,Privat,Kort,KND-41689,Levererad,NaN,NaN,NaN
855,ORD-2024-00531,ORD-2024-00531-2,2024-07-16,2024-07-19,SKU-MN003,"Bildskärm 32"" Curved",Bildskärmar,1,5999 kr,UPPSALA,Privat,Swish,KND-61712,Levererad,"Leverans på två dagar, imponerad!",28 juli 2024,5.0
2746,ORD-2024-01646,ORD-2024-01646-2,"February 01, 2024",2024-02-04,SKU-MN001,"Bildskärm 27"" UHD",Bildskärmar,1,4999.00,Stockholm,Privat,Faktura,KND-92109,Levererad,Medelmåttig upplevelse.,8 februari 2024,3.0
604,ORD-2024-00375,ORD-2024-00375-2,2024-01-05,2024-01-08,SKU-LP001,Laptop Pro 15,Datorer,1,14999.00,Stockholm,Privat,Swish,KND-44657,Levererad,NaN,NaN,NaN
2372,ORD-2024-01418,ORD-2024-01418-2,2024-07-02,2024-07-05,SKU-HS002,Headset Budget,Ljud,1,499.00,göteborg,PRIVAT,Kort,KND-27754,Levererad,NaN,NaN,NaN
1926,ORD-2024-01159,ORD-2024-01159-1,14 december 2024,2024-12-17,SKU-SD002,Extern SSD 500GB,Lagring,1,699.00,ÖREBRO,Privat,Kort,KND-69711,Levererad,Toppen! Exakt vad jag behövde.,2024-12-21,4.0
789,ORD-2024-00489,ORD-2024-00489-2,2024-02-19,2024-02-22,SKU-HS002,Headset Budget,Ljud,1,499.00,Stockholm,Företag,Faktura,KND-83717,Levererad,NaN,NaN,NaN
2585,ORD-2024-01547,ORD-2024-01547-1,2024-12-08,2024-12-11,SKU-MN001,"Bildskärm 27"" UHD",Bildskärmar,1,4999.00,Örebro,PRIVAT,Faktura,KND-81067,Levererad,NaN,NaN,NaN
402,ORD-2024-00250,ORD-2024-00250-1,2024-11-20,2024-11-17,SKU-KB001,Mekaniskt Tangentbord K7,Tillbehör,1,1299.00,Malmö,privat,Faktura,KND-56094,Levererad,NaN,NaN,NaN
1938,ORD-2024-01166,ORD-2024-01166-3,2024/02/03,2024-02-06,SKU-SP001,Bluetooth-högtalare,Ljud,1,899.00,Göteborg,Privat,Kort,KND-38153,Levererad,NaN,NaN,NaN

In [38]:
df_raw["region"].value_counts()

region
Stockholm     834
Göteborg      434
Malmö         236
Uppsala       192
Norrland      125
Örebro        117
Linköping     117
Västerås       75
STOCKHOLM      50
Sthml          44
stockholm      42
STHLM          39
uppsala        25
Sthlm          25
göteborg       24
GÖTEBORG       22
UPPSALA        21
Gothenburg     19
MALMÖ          16
Gbg            14
malmo          12
LINKÖPING      11
GBGB           11
Orebro         10
Vasteras       10
örebro          9
ÖREBRO          9
norrland        9
linköping       8
NORRLAND        8
Malmo           8
Linkoping       8
västerås        7
Norr            7
VÄSTERÅS        7
malmö           7
Name: count, dtype: int64

In [39]:
df_raw["kundtyp"].value_counts()

kundtyp
Privat       1535
Företag       783
privat         66
b2c            64
Konsument      60
PRIVAT         58
B2C            45
B2B            39
b2b            35
FÖRETAG        29
Firma          27
företag        26
Name: count, dtype: int64

In [40]:
df_raw["betalmetod"].value_counts()

betalmetod
Faktura           938
Kort              775
Swish             550
Invoice            51
FAKTURA            50
faktura            44
Kreditkort         36
KORT               33
SWISH              31
swish              31
kort               30
Mobilbetalning     29
Visa               28
Mastercard         25
Name: count, dtype: int64

In [41]:
df_raw["leveransstatus"].value_counts()

leveransstatus
Levererad          2005
Under transport     152
Retur               132
Skickad              95
Mottagen             92
levererad            86
LEVERERAD            68
Returnerad           10
Återsänd              8
På väg                7
retur                 6
under transport       6
RETUR                 4
UNDER TRANSPORT       2
Name: count, dtype: int64

In [25]:
df_raw["orderrad_id"].isna().sum()

np.int64(0)

In [ ]:
df_raw.duplicated().sum()

np.int64(67)

In [27]:
df_raw["orderrad_id"].duplicated().sum()

np.int64(67)

In [31]:
df_raw["order_id"].duplicated().sum()

np.int64(1110)

In [29]:
dupes = df_raw[df_raw["orderrad_id"].duplicated(keep=False)].sort_values("orderrad_id")
dupes.head(10)

,order_id,orderrad_id,orderdatum,leveransdatum,produkt_sku,produktnamn,kategori,antal,pris_per_enhet,region,kundtyp,betalmetod,kund_id,leveransstatus,recension_text,recensionsdatum,betyg
613,ORD-2024-00070,ORD-2024-00070-1,2024-11-18,2024-11-20,SKU-KB002,Kompakt Tangentbord Mini,Tillbehör,1,599.00,Stockholm,Privat,Kort,KND-13904,Levererad,Riktigt nöjd! Använder den dagligen.,2024-11-23,4.0
107,ORD-2024-00070,ORD-2024-00070-1,2024-11-18,2024-11-20,SKU-KB002,Kompakt Tangentbord Mini,Tillbehör,1,599.00,Stockholm,Privat,Kort,KND-13904,Levererad,Riktigt nöjd! Använder den dagligen.,2024-11-23,4.0
181,ORD-2024-00110,ORD-2024-00110-1,2024-07-11,2024-07-14,SKU-MS001,Trådlös Mus X1,Tillbehör,2,399 kr,Gbg,privat,Kort,KND-13544,Levererad,"Leverans på två dagar, imponerad!",2024-07-21,4.0
1403,ORD-2024-00110,ORD-2024-00110-1,2024-07-11,2024-07-14,SKU-MS001,Trådlös Mus X1,Tillbehör,2,399 kr,Gbg,privat,Kort,KND-13544,Levererad,"Leverans på två dagar, imponerad!",2024-07-21,4.0
2003,ORD-2024-00111,ORD-2024-00111-1,2024-06-21,2024-06-26,SKU-MN002,"Bildskärm 24"" FHD",Bildskärmar,1,2499.00,NORRLAND,Företag,Faktura,KND-39076,Levererad,Leveransskada - kartongen var helt demolerad.,2024-07-06,2.0
182,ORD-2024-00111,ORD-2024-00111-1,2024-06-21,2024-06-26,SKU-MN002,"Bildskärm 24"" FHD",Bildskärmar,1,2499.00,NORRLAND,Företag,Faktura,KND-39076,Levererad,Leveransskada - kartongen var helt demolerad.,2024-07-06,2.0
224,ORD-2024-00138,ORD-2024-00138-2,2024-09-17,2024-09-21,SKU-HS002,Headset Budget,Ljud,2,499.00,Linköping,b2b,Kort,KND-41713,Levererad,Fungerar inte som det ska. Måste returnera.,2024-09-29,1.0
1682,ORD-2024-00138,ORD-2024-00138-2,2024-09-17,2024-09-21,SKU-HS002,Headset Budget,Ljud,2,499.00,Linköping,b2b,Kort,KND-41713,Levererad,Fungerar inte som det ska. Måste returnera.,2024-09-29,1.0
276,ORD-2024-00168,ORD-2024-00168-2,2024-07-31,2024-08-02,SKU-MS002,Ergonomisk Mus Pro,Tillbehör,1,699.00,Göteborg,privat,Faktura,KND-30388,Levererad,Prisvärt och bra kvalitet. Kommer köpa igen.,2024-08-14,5.0
383,ORD-2024-00168,ORD-2024-00168-2,2024-07-31,2024-08-02,SKU-MS002,Ergonomisk Mus Pro,Tillbehör,1,699.00,Göteborg,privat,Faktura,KND-30388,Levererad,Prisvärt och bra kvalitet. Kommer köpa igen.,2024-08-14,5.0

In [30]:
(df_raw[["order_id", "orderrad_id"]]
 .duplicated()
 .sum())

np.int64(67)

In [32]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 2767 entries, 0 to 2766
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         2767 non-null   str
 1   orderrad_id      2767 non-null   str
 2   orderdatum       2767 non-null   str
 3   leveransdatum    2767 non-null   str
 4   produkt_sku      2767 non-null   str
 5   produktnamn      2767 non-null   str
 6   kategori         2767 non-null   str
 7   antal            2767 non-null   str
 8   pris_per_enhet   2767 non-null   str
 9   region           2612 non-null   str
 10  kundtyp          2767 non-null   str
 11  betalmetod       2651 non-null   str
 12  kund_id          2767 non-null   str
 13  leveransstatus   2673 non-null   str
 14  recension_text   1355 non-null   str
 15  recensionsdatum  1355 non-null   str
 16  betyg            1355 non-null   float64
dtypes: float64(1), str(16)
memory usage: 367.6 KB

# EDA

1. Orderrad_id är unikt och är datasetets grain, men det finns dubletter som behöver hanteras.

2. Orderdatum är en sträng som behöver göras om till datetime, samma gäller för leveransdatum. 

3. Antal ska ändras om till en int. 

4. Pris_per_enhet ska göras om till float. 

5. Region beöver standardiseras och nullvärden hanteras. 

6. Kundtyp behöver standardiseras till rätt namn. 

7. betalmetod behöver standardiseras till rätt namn

8. Leveransstatus behöver standardiseras till rätt namn.

9. Behöver göra om recensionsdatum till datetime.

In [ ]:
#1. fixa dubletter i orderrader
def clean_orderrader(df):
    df_clean = df.copy()
    # Ta bort dubbletter baserat på 'orderrad_id'
    before = len(df_clean)
    df_clean = df_clean.drop_duplicates().reset_index(drop=True)
    after = len(df_clean)

    print(f"Tagit bort dubletter: {before - after}")

    return df_clean

Tagit bort dubletter: 67

In [ ]:
#2. fixa orderdatum
def clean_orderdatum(df):
    df_clean = df.copy()
    
    # Konvertera "orderdatum" till datetime-format
    df_clean['orderdatum'] = pd.to_datetime(
        df_clean['orderdatum'], 
        dayfirst=True, 
        format="mixed", 
        errors='coerce')

    # Här hanterar vi ogiltiga datum genom att sätta dem till NaT
    invalid_dates = df_clean['orderdatum'].isna().sum()
    if invalid_dates > 0:
        print(f"Hittade {invalid_dates} ogiltiga datum i 'orderdatum', sätter dessa till NaT.")

    return df_clean

In [ ]:
#2.1 fixa leveransdatum
def clean_leveransdatum(df):
    df_clean = df.copy()
    
    # Konvertera 'leveransdatum' till datetime-format
    df_clean['leveransdatum'] = pd.to_datetime(
        df_clean['leveransdatum'], 
        dayfirst=True, 
        format="mixed", 
        errors='coerce')

    # Här hanterar vi ogiltiga datum genom att sätta dem till NaT
    invalid_dates = df_clean['leveransdatum'].isna().sum()
    if invalid_dates > 0:
        print(f"Hittade {invalid_dates} ogiltiga datum i 'leveransdatum', sätter dessa till NaT.")

        

    return df_clean

In [48]:
#3.
def clean_antal(df):
    df_clean = df.copy()
    
    # Konvertera 'antal' till numeriskt format
    df_clean['antal'] = pd.to_numeric(
        df_clean['antal'], 
        errors='coerce')

    # Hantera negativa och nollvärden
    invalid_antal = (df_clean['antal'] <= 0).sum()
    if invalid_antal > 0:
        print(f"Hittade {invalid_antal} ogiltiga värden i 'antal' (negativa eller noll), sätter dessa till NaN.")
        
        df_clean.loc[df_clean['antal'] <= 0, 'antal'] = np.nan

    df_clean["antal"] = df_clean["antal"].astype("Int64")

    return df_clean

In [64]:
#4.
def clean_pris(df):
    df_clean = df.copy()
    
    # Konvertera 'pris' till numeriskt format
    df_clean['pris'] = pd.to_numeric(
        df_clean['pris'], 
        errors='coerce')

    # Hantera negativa och nollvärden
    invalid_pris = (df_clean['pris'] <= 0).sum()
    if invalid_pris > 0:
        print(f"Hittade {invalid_pris} ogiltiga värden i 'pris' (negativa eller noll), sätter dessa till NaN.")
        
        df_clean.loc[df_clean['pris'] <= 0, 'pris'] = np.nan

    return df_clean

In [63]:
#5.
def standardisera_region(df):
    df_clean = df.copy()
    df_clean["region_raw"] = df_clean["region"]

    def klassificera_region(val):
        if pd.isna(val):
            return "Okänd"

        v = str(val).lower().strip()

        if v in ["stockholm", "sthlm", "sthl", "sthml"]:
            return "Stockholm"

        if v in ["uppsala"]:
            return "Uppsala"

        if v in ["göteborg", "gothenburg", "gbg", "gbgb"]:
            return "Göteborg"

        if v in ["malmö", "malmo"]:
            return "Malmö"

        if v in ["norrland", "norr"]:
            return "Norrland"

        if v in ["örebro", "orebro"]:
            return "Örebro"

        if v in ["västerås", "vasteras"]:
            return "Västerås"

        if v in ["linköping", "linkoping"]:
            return "Linköping"

        return "Okänd"

    df_clean["region"] = df_clean["region"].apply(klassificera_region)
    return df_clean

In [ ]:
#7.

In [ ]:
#8.

In [ ]:
#9.